### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#103]
- [x] Delete the tags fixture and remove the command to import this fixture from the readme
- [ ] Create a fresh database and populate it with a few test users (admin, standard, premium), dump to a new fixture
- [x] Show a table on the readme for these users with credentials and a short desc
- [x] Move the fixture section to be after migrations
- [x] Add section about contributing
- [x] Add section about roadmap

**Comment by keyxcode** [comment]
I would also consider the following things:
- Clean up the commands so they're easier to copy paste ($ or space at the beginning)
- Add the redis installation guide for Mac: https://redis.io/docs/getting-started/installation/install-redis-on-mac-os/
- Add a note that it might be necessary to `createuser` and grant privilege first before `createdb` https://stackoverflow.com/questions/30641512/create-database-from-command-line
