### ISSUE TITLE
Verify emails automatically

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#12]
Every user who has verified their email address on the older project has the profile flag `is_verified` set to True. It would be nice to use this flag and programmatically verify all email addresses for user accounts that have been verified.

**Comment by keyxcode** [comment]
I would love to try tackling this one!

**Comment by keyxcode** [comment]
Hi @danielzeljko I realized there was an issue with the script but after reading your comment I still couldn't quite understand what needs to be done. The way I see it, user email addresses are already in the EmailAddress table so I don't get why an adding step is necessary here. Could you please elaborate? Thanks a lot!

> this command is not programmatically adding emails to the EmailAddress table. It's only setting the verified flag for already existing email addresses.

**Comment by danielzeljko** [comment]
Great question. Email addresses get stored in the `EmailAddress` table under two* conditions:
1. When a user registers through the Allauth registration form
2. When a user attempts to log in

Users created before migrating the codebase bypassed these steps. THis also happens if you were to create superuser accounts using the following command:

    python manage.py createsuperuser
 
 If you check the `EmailAddress` table with the following shell commands:
 
    from allauth.account.models import EmailAddress
    EmailAddress.objects.all()

You'll notice that these manually created users won't have corresponding entries in the `EmailAddress` table. Then if you try to log in, you will notice that it will send a confirmation email and that email will be present in this table. So you will need to programmatically add the emails to the `EmailAddress` table if they do not exist.

*These are my observations without digging into the allauth source code
