### ISSUE TITLE
Pagination panel doesn't show the Previous page button

### ISSUE THREAD

**Issue by chrismathew047** [LangCorrect/server#125]
The pagination panel does not show the previous page button when I navigate to other pages. This makes it difficult to go back to the first page without using the back arrow. See the attached images for reference.

![image](https://github.com/LangCorrect/server/assets/115909094/8f497340-9ead-4c7e-8509-5c213aec76f8)
![image](https://github.com/LangCorrect/server/assets/115909094/af9b3042-938b-41d9-8284-99fe4dd49b90)
![image](https://github.com/LangCorrect/server/assets/115909094/4f41e5dc-c9ac-4478-89a8-341b79ea29d9)

**Comment by ChrisJoel10** [comment]
Hello @danielzeljko, can I work on this?

**Comment by danielzeljko** [comment]
Hey @ChrisJoel10, thank you for bringing it to my attention. I've assigned this issue to you. Feel free to reach out if you have any questions. Thanks for the help!

**Comment by danielzeljko** [comment]
Hi @ChrisJoel10, I'm just checking in to see how it's going. Do you need any help?

**Comment by itshesam** [comment]
i can take it if the issue needed to be reassigned

**Comment by danielzeljko** [comment]
If there's no response within the next 12 hours feel free to take over this issue @itshesam
