### ISSUE TITLE
Verify Japanese Translations

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#134]
### Description:
The translations for this locale need to be verified for accuracy and context suitability.

### Tasks:
- [ ] Review all strings for grammatical errors
- [ ] Ensure that translations fit the context where they are used
- [ ] Correct any ambiguous phrases

**Comment by masatami** [comment]
In the list of language levels both "Elementary" and "Beginner" are translated as 初級. I propose changing beginner to 初心者, as it makes it clear that the person just started learning the selected language, while 初級 can remain equivalent to elementary as in "this person has at least some knowledge about the language".

**Comment by danielzeljko** [comment]
I've updated the translations. Thanks for letting me know!
