### ISSUE TITLE
[WIP] Implement Account Deletion with Stripe Subscription Cancellation

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#147]
Create a view and update the UI to allow users to delete their accounts. The process should also cancel any active Stripe subscriptions, wipe out all personal information, and mark the user as inactive.

Acceptance Criteria:

- User can initiate account deletion from the UI.
- Active Stripe subscriptions are canceled upon account deletion.
- All personal information is wiped clean.
- User is marked as inactive.
- User is informed about what will happen upon account deletion.

Tasks:

- [ ] Create a new view for account deletion.
- [ ] Update the UI to include an "Delete Account" option.
- [ ] Implement Stripe subscription cancellation.
- [ ] Wipe out all personal user information.
- [ ] Mark the user as inactive.
- [ ] Add a confirmation dialog or step to inform the user about the deletion effects.

Code Snippet from Old View (f-strings preferred):

```
        user.is_active = False
        user.is_staff = False
        user.is_superuser = False
        user.username = "deleted_user_{}".format(user.id)
        user.email = "deleted_user_{}@langcorrect.com".format(user.id)
        user.first_name = ""
        user.last_name = ""
        user.bio = ""
        user.nick_name = ""
        user.save()
```

Additional Notes:

Ensure compliance with GDPR or other data protection laws for account deletion.

![image](https://github.com/LangCorrect/server/assets/115326106/4075a346-c912-43b4-8531-ecf206513e3e)

**Comment by daniesteban** [comment]
Where could I find the option to delete an account? The issue is marked as completed, but I can't find any place in my profile webpage to delete it. Maybe it is lost due to some UI change?
Could you help me? Thanks.
