### ISSUE TITLE
Remove "Following feed" Sidebar

### ISSUE THREAD

**Issue by keyxcode** [LangCorrect/server#152]
With the addition of the Following filter in the main feed, I believe the "Following feed" sidebar is no longer needed and we should remove it in order to declutter the look of the new app.
![image](https://github.com/LangCorrect/server/assets/102985900/f5a04371-10f5-4f29-b23e-720b21caf54a)

**Comment by danielzeljko** [comment]
One of the advantages of having the following feed in the sidebar is that it provides quick visibility for any uncorrected journal entries from people you're following. However, you do make a valid point about reducing clutter. We'll proceed with the removal for now to test the waters. If we start receiving complaints, we can reintroduce it later or offer it as a personalization option via settings.
