### ISSUE TITLE
The UI for adding a reply to a correction is not very clear

### ISSUE THREAD

**Issue by precondition** [LangCorrect/server#157]
At first, I thought that the feature was removed but then I started clicking at random around the correction and managed to open the reply-text-box hidden in the dropdown.

I think it would work better to add an explicit button that you can click instead of hiding the text field in a dropdown with supposedly 0 elements (you wouldn't expect anything to happen when clicking an empty dropdown)

**Comment by danielzeljko** [comment]
Thank you for the feedback! Are you able to create a quick sketch of what your proposed version would look like? We can also revert the design back to how it used to look in the old codebase where the accordion (dropdown) was hidden and the form to write a reply was shown directly.
