### ISSUE TITLE
Update logout icon

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#163]
![image](https://github.com/LangCorrect/server/assets/115326106/5d2a9c6b-baca-4ab8-9ae1-289fe501f255)

    <i class="fa-solid fa-right-from-bracket"></i>

**Comment by itshesam** [comment]
i made a pull request https://github.com/LangCorrect/server/pull/164

Thanks for the tag, that's actually my first github pull request

**Comment by itshesam** [comment]
i made a pull request https://github.com/LangCorrect/server/pull/165

Thanks for the tag, that's actually my first github pull request
