### ISSUE TITLE
Bonus correction point system 

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#174]
> jeffccy
> 
> The original intention for this to come up in my mind is that I’m desperate for people to correct my journals, especially those who are willing to explain my mistakes with reasons as most of you may relate when expressing the same sentence in different language, there are a lot of cultural nuances that may affect the structure that may be widely different from what we have learnt.
> 
> So here’s my suggestion:
> We can implement it as follows,
> (1) Bonus correction points for reaching X threshold and reset in daily basis.
> The way it works is basically self-explanatory, a corrector reaches a correction point threshold, then additional bonus point will be given to the corrector for the additional corrections made on that day as an incentive for correcting. This incentive should be large enough to encourage corrector to do corrections on already-corrected-journals - so corrected journals may benefit from more corrector(s) correcting their work.
> 
> (2) Bonus correction point given to corrector if journal author gives credit
> So, in order to make it more positive, I propose that all journal creator can award a “star” to the corrector if he/she sees fit. The star then will award the corrector additional bonus point for that particular journal, this will hopefully foster corrector giving more elaborate explanation on the corrections made, instead of blitzing through the journals, which is why the incentive for this should be larger than method (1). OR the star can serve as a token for which it can be used by recipient to transform that “currency” into correction points to boost the ratio.
> 
> Initial idea was to cope with mere 1-2 corrections made on each journal, especially more in languages that are not as populated as in English. Originally I was thinking BP (bonus point) will be awarded to corrector if they correct a journal that’s already been corrected twice; but I fear it will discourage people from correcting the journal right away, and it would turn into a less healthy reciprocation system.
> 
> I understand that this may be a overly complicated system and I’m not even sure if this is doable. But I suggest this from a user standpoint, and of course, the intention to get better in foreign language.

**Comment by mahumt** [comment]
I also want to add. I understand the correction ratio is there to ensure that person engages in a fair "give and take". but the ratio is based on how many corrections you receive vs provide. Rather than how many texts you correct. 
Some texts dont require a lot of correction; the corrector in that case should add some additional feedback to improve the writing to take it to the next level. But right now that doesn't count towards the ratio, in that case you end up scouring the feed for more correction and end up doing a lot more corrections than a text requires to get the ratio up.

**Comment by danielzeljko** [comment]
How would you quantify the effectiveness of feedback, though? It's challenging to measure whether feedback has elevated a text to the next level. The only way I can imagine that might work is via a server like ChatGPT API, but that costs money and its responses aren't always accurate.

**Comment by mahumt** [comment]
Chatgpt might be a bit too much :) 
Maybe we leave that up to the poster?
A 1,2,3 rating system. Or a "useful or not" toggle button. 
I am purposing this becuase i have definetly left additional freedback on the whole of text that i thought was more useful then actual corrections. In some cases i was able to point out what to try next to level up or what the text's focus should be. Thats not something people add in the sentence by stence correction sections

**Comment by danielzeljko** [comment]
I’m closing this since our new ratio formula makes it easy to achieve high ratios.
