### ISSUE TITLE
Project containerization

### ISSUE THREAD

**Issue by itshesam** [LangCorrect/server#182]
Is there any plan to containerize the project with docker ?

**Comment by danielzeljko** [comment]
I'm not yet familiar enough with Docker, but I do see the value it could bring to the project especially when it comes to contributors building and running the project.

**Comment by itshesam** [comment]
yea easier setup is one of its benefits. so i assume that you'd like to do it yourself if you ever decide to do so.

**Comment by SufyaanKhateeb** [comment]
I could try to implement it. Maybe we could start slowly by just doing it for the frontend and then slowly incorporate the backend.
Containerizing is not only good for building and running, deploying and scaling would also be potential reasons for doing this. I am no expert in this but I can try to do it?

**Comment by danielzeljko** [comment]
I'm happy that there's quite some interest in this. I'm totally fine with someone else working on this issue, but I unfortunately won't be able to provide any help or guidance as I am yet not familiar enough with containerization/docker, and what it takes to maintain a project that uses it.

If someone would like to take on this task, I'd be more than supportive of it. However, I would need _detailed_ documentation. So, please include a step-by-step guide that explains the Docker setup process, how to build, update, and run the containers, and any changes made to the existing project structure. How much downtime would be expected during this migration process?

Notes:
- The server is run on a DigitalOcean droplet that is running Ubuntu v22.04

**Comment by danielzeljko** [comment]
Progress with containerization has been made. 

These are the things remaining:
- installing required fixtures
- generating mock data during installation (#403) (It would be nice to have an argument we can pass to skip this)
- testing to see if everything is working correctly and reviewing configurations
- updating documentation and getting started
- pushing to prod

If anyone is interested in helping out, feel free to reach out!
