### ISSUE TITLE
Permission needed to be checked when updating a post

### ISSUE THREAD

**Issue by itshesam** [LangCorrect/server#190]
When a user is updating a post(or delete), it should be checked that the post is his, otherwise it's possible to edit other's posts.

**Comment by danielzeljko** [comment]
Thank you for raising this security concern. Right now, we're using a queryset filter that only allows authors to see and edit their posts: https://www.django-antipatterns.com/antipattern/checking-ownership-through-the-userpassestestmixin.html. It should return a 404 if someone tries to edit or delete a post that isn't theirs. Have you found a way to get around this?

**Comment by itshesam** [comment]
actually you're right and everything is ok. 
i tweaked the get_queryset a bit to show another's post to the current user and that worked, but it seems that it was the key and 404 page is shown if such thing happens. you can close this.
