### ISSUE TITLE
Remove forums from community dropdown

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#192]
We need to remove this as the forum has been shut down permanently.

![image](https://github.com/LangCorrect/server/assets/115326106/04b19177-60c3-4f11-89b6-5b237cec543a)

**Comment by gaurab-khanal** [comment]
Can I work on this?

**Comment by AbhishekMaurya2002** [comment]
can you assign me Please

**Comment by danielzeljko** [comment]
I've assigned this issue to @gaurab-khanal as they were the first to ask.

**Comment by gaurab-khanal** [comment]
@danielzeljko I just made a PR. Can you review it?
