### ISSUE TITLE
I can’t login LangCorrect. 

### ISSUE THREAD

**Issue by jack342101** [LangCorrect/server#195]
My email can’t receive the verification messages from LangCorrect. 

I haven't posted essays in the past few days. When I opened LangCorrect website yesterday morning, it required me to input my username and password. After I did that, it said it had sent a verification email to me and I needed to complete the verification. But I never saw the message in my inbox. I logged in many times and all had the same results. I also checked my blocklist, no LangCorrect. I can receive verification emails from other websites. So far I am still not able to login to LangCorrect. I am going crazy.

**Comment by jack342101** [comment]
I hope someone helps me out. I am going crazy.

**Comment by keyxcode** [comment]
Sorry for the inconvenience @jack342101 Could you please send us your email address at support[at]langcorrect.com
We will look into this asap @danielzeljko

**Comment by jack342101** [comment]
Username: Jack or 3421011966
Email: ***@***.***
Thanks.&nbsp;



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: CP ***@***.***&gt;
Date: Thu, Oct 12, 2023 1:18 PM
To: LangCorrect/server ***@***.***&gt;
Cc: jack342101 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [LangCorrect/server] I can’t login LangCorrect.  (Issue #195)





 
Sorry for the inconvenience @jack342101 Could you please send us your email address at support[at]langcorrect.com
 We will look into this asap @danielzeljko

**Comment by Serhannnnn** [comment]
I cannot login Langcorrect for a couple of days. What 's wrong with Langcorrect?

**Comment by GiovanniSmith** [comment]
I'm getting the same error. Upon trying to log in, it gives me the error "The username and/or password you specified are not correct." I autofill my username and password with my password manager, so I know that they haven't changed.

**Comment by danielzeljko** [comment]
I manually verified @jack342101's email address, and now he's able to log in.

@Serhannnnn  @GiovanniSmith can you provide some more information. Have you verified your email addresses with the new system? If not, are you having trouble receiving the confirmation email? If so, please send me an email using the email you registered the account with along with the username to support[at]langorrect.com.

**Comment by danielzeljko** [comment]
Thanks for being patient! Once #180 gets merged into the main branch and ran, everyone who has verified their email addresses previously will not have to do it again in the new system.

**Comment by danielzeljko** [comment]
All previously verified email addresses are now verified in the new system. Please also make sure you are signing with your actual username (not nickname) and password. Unlike the old version, we currently do not support signing in with an email address in place of a username.
