### ISSUE TITLE
Notifications of other members

### ISSUE THREAD

**Issue by quircks** [LangCorrect/server#196]
I believe I can see notifications of other people. I don't know whether it's by design, but I'd expect the bell button in the upper-right corner to show my own notifications. But if I navigate to some other user's profile and press this button, I can see what seems to be their notifications, not mine.
![Screenshot](https://github.com/LangCorrect/server/assets/79171569/7cfebd44-2cdb-4728-8c2b-852901319f1a)

**Comment by danielzeljko** [comment]
Thanks for the report. I'll look into this shortly.
