### ISSUE TITLE
Various post card issues

### ISSUE THREAD

**Issue by keyxcode** [LangCorrect/server#198]
- Post card with native text doesn't truncate when viewed from user profile page
- There's a "Correct" button even for posts that aren't in the user's native languages. This will take them to a 403 page. It would be better UX to have a small symbol there to indicate that this post can't be corrected by the user. Here's a mock-up
<img width="965" alt="image" src="https://github.com/LangCorrect/server/assets/102985900/20d01ae5-db8d-4718-b0e7-ad3a70d4a5d7">

**Comment by danielzeljko** [comment]
I like that idea. I do wonder if it would be better in this case to keep the button icon and text as it is and just disable the button. I would replace `journals` with `entries` to make it less confusing for people.

**Comment by danielzeljko** [comment]
What if we combined the two? I think we should keep the "correct" button text for consistency and to ensure users always know the button's primary function. I do like the ban icon you're suggesting because it immediately signals that some action is prohibited, and that would pair nicely with the disabled button. How would that look like?

**Comment by keyxcode** [comment]
Here's what it would look like @danielzeljko 
<img width="442" alt="image" src="https://github.com/LangCorrect/server/assets/102985900/2cb6a06a-0d7f-4554-9e39-2521383e4b96">

**Comment by danielzeljko** [comment]
I think it's not bad! What are your honest thoughts about it?

**Comment by keyxcode** [comment]
At the beginning I much preferred the plain ban icon, but after seeing them all now I'm not sure tbh 😂
This might be a good one to ask the staff for their opinions

**Comment by danielzeljko** [comment]
Let's go with the icon and text for now, and we can revisit this as the feedback comes in.

Also, I found one more issue with the postcard. The tags are not showing up. Can you add that with your PR?

**Comment by keyxcode** [comment]
Can you provide a screenshot of these tags in the old site? I don't think I've ever used this feature.

**Comment by danielzeljko** [comment]
![image](https://github.com/LangCorrect/server/assets/115326106/2eda38eb-1ca6-462e-9bd5-1bc98761d949)

These tags used to be clickable in the old site, but I think that functionality should be a separate issue altogether.

**Comment by keyxcode** [comment]
In that case the PR's ready @danielzeljko
