### ISSUE TITLE
Native text entry is not shown in correction page

### ISSUE THREAD

**Issue by socio-trivia** [LangCorrect/server#246]
English entry in the post: https://langcorrect.com/journals/%E3%83%8E%E3%83%BC%E3%82%B9-north/ is not shown in its correction page: https://langcorrect.com/journals/%E3%83%8E%E3%83%BC%E3%82%B9-north/make_corrections.

It would be helpful to have native text entry there for better correction.

**Comment by danielzeljko** [comment]
Thank you for the feedback. I'll work on this issue soon!
