### ISSUE TITLE
Task to Periodically Update is_corrected Flag on Post Object

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#26]
Currently, the `is_corrected` flag on a Post object is set to `True` when a native speaker corrects the post. However, if all corrections are later removed, the flag remains `True` instead of reverting back to `False`.

To resolve this, we can periodically run a task to check if a post has corrections and change the flag as needed. Alternatively, we can use a signal but this would increase the system's complexity.

**Comment by itshesam** [comment]
maybe i'm missing something, but why can't we just check it when users remove their corrections ?

**Comment by danielzeljko** [comment]
You're right and that's a great approach for future removals. However, we would still need to run a management command once so that we can recalculate the flag for past removals. Would this be something you're interested in tackling?

**Comment by itshesam** [comment]
yeah, that's ok, i would like to work on it. so first i check the condition when some user delete the correction and as you said we can make a management command to correct past removals.

i may have questions if i encounter any problems, so i will ask them here if i have any.

**Comment by danielzeljko** [comment]
I've assigned this issue to you. Feel free to reach out if you have any questions. I'll be flying out for a trip tomorrow, but I'll be in two days. Feel free to join our discord if you need to get in contact with me sooner. The link is in the footer!
