### ISSUE TITLE
Two different names

### ISSUE THREAD

**Issue by schlaudermeister** [LangCorrect/server#285]
There are two different names of mine that the other users can see. One is my name in the rankings and the other one can be seen when I write or correct a text. How can I change the name in the rankings?

**Comment by keyxcode** [comment]
Thanks for the report @schlaudermeister ! This is being actively looked at at the moment and should be resolved after we're done with #267

**Comment by schlaudermeister** [comment]
Thanks a lot!

 
 

Gesendet: Samstag, 02. Dezember 2023 um 17:18 Uhr
Von: "CP" ***@***.***>
An: "LangCorrect/server" ***@***.***>
Cc: "schlaudermeister" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [LangCorrect/server] Two different names (Issue #285)


 

Closed #285 as completed.
