### ISSUE TITLE
similar sentences shown in correction page

### ISSUE THREAD

**Issue by socio-trivia** [LangCorrect/server#294]
In https://langcorrect.com/journals/going-home-%E5%AE%B6%E3%81%AB%E5%B8%B0%E3%82%8B%E6%99%82/make_corrections,
"今回は友人の頭が痛いから、Uberをして町に行った。" and "今回は友人の頭が痛いので、Uberをして町に行った。" are shown. 

The original is "今回は友人の頭が痛いので、Uberをして町に行った。".

**Comment by danielzeljko** [comment]
We need to hide old sentences that no longer appear in a post's text after it's been edited. `PostRow` has a field called `is_actual` that will need to be updated accordingly.

**Comment by danielzeljko** [comment]
Fixed by #347
