### ISSUE TITLE
Inconsistencies with usernames

### ISSUE THREAD

**Issue by kayomi-codes** [LangCorrect/server#308]
![user_example_bug.jpg](https://github.com/LangCorrect/server/assets/132253104/cabc08ea-ddc9-4cfc-9a19-4bc862021516)

Task:

- [ ] Update to use the `user.display_name` property

**Comment by kayomi-codes** [comment]
Other images:
![IMG_20231110_105517.jpg](https://github.com/LangCorrect/server/assets/132253104/ea451d4e-7a08-4c3b-831a-80dc9b0b228b)

**Comment by danielzeljko** [comment]
Now that you mention it, the `first_name` and `last_name` fields aren't displayed anywhere actually. This information is only used for recovering an account. Maybe we should privately show/display this information somewhere other than settings.

**Comment by kayomi-codes** [comment]
I see, thank you for answering. If those fields aren't shown anywhere, what
is the field of the name that is displayed in the second photo I attached
(in the comments) and the one that appears in the blue bar? I believe
people would like a feature that allows them to change their nickname and
username as this is often done in other social media platforms.

**Comment by Raithlin** [comment]
I'd like to give this a go. Are you wanting just the one change (in `navbar`), or would you prefer I search for all UI references to user.username?

**Comment by danielzeljko** [comment]
Let's search for all UI references and update them to use `display_name` for consistency. I'm not really sure where the `first_name` would be preferable, but I do see how it could make things more personal. The only issue with this is that not many users have added a first/last name.

**Comment by Raithlin** [comment]
Perhaps we can use `username` as a fallback.

**Comment by Raithlin** [comment]
I've made all the UI changes - however, the real problem lies in `/users/models.py`: 
`def display_name(self):
        return self.nick_name if self.nick_name else self.username`

As you can see, no reference to first of last name here. Nor is `nick_name` referenced anywhere else besides `seed.sql`, so it is probably never populated. I guess that's another ticket though.

**Comment by Raithlin** [comment]
@danielzeljko Do I need permissions to create a branch (308-correct-user-display-name) on this project, or do I fork the project and create a PR from that?

**Comment by danielzeljko** [comment]
I've updated this issue to better reflect the core issue which was inconsistencies with usernames/display names. I think we should refrain from updating the display_name function as to not leak a user's personal information.

Thanks for contributing and the help! 🙌
