### ISSUE TITLE
Typeface: Don't use Noto Sans JP for Chinese entries

### ISSUE THREAD

**Issue by yue-dongchen** [LangCorrect/server#310]
## Problem
At present, Chinese-language entries are jarring to read, as

1. most of the characters are taken from `Noto Sans JP`, but many are missing from Noto Sans JP, which fall back to some other font, causing inconsistency
![](https://i.ibb.co/0KB2dNk/Screenshot-2023-11-12-110201.png)
![Fonts in the CSS stylesheets](https://i.ibb.co/SKgrBzx/Screenshot-2023-11-12-110236.png)
Missing characters as shown using the Google Fonts preview:
![Missing characters as shown using the Google Fonts preview](https://i.ibb.co/k6gPvLn/Screenshot-2023-11-12-111116.png)
2. with `Noto Sans JP` being a Japanese oriented typeface, it's just not a nice experience for reading Chinese-language content.

## Wish
Use _Noto Sans Simplified Chinese_ if the specified post language is `zh-hans`, _Noto Sans Traditional Chinese_ for `zh-hant`; and _Noto Sans JP_ if it's Japanese; if unspecified, use only _Noto Sans_. This can be done through language-specific styling by adding the `lang` attribute onto posts based on specified language, and adding language-specific CSS. See https://www.w3.org/International/questions/qa-css-lang.en.html

**Comment by danielzeljko** [comment]
This is an absolutely wonderful issue! Thank you for also teaching me about language-specific CSS and including a link to a resource :D

**Comment by danielzeljko** [comment]
I've added the `lang` attribute to posts, corrections, make a correction page, and the text overview modal. I might have forgotten to add it somewhere, but we can worry about it afterward!
