### ISSUE TITLE
Typeface: Text alignment for RTL languages like Arabic

### ISSUE THREAD

**Issue by yue-dongchen** [LangCorrect/server#311]
## Problem
Edit: It's not really a typeface issue — mistype, should be more generally "typesetting"
LangCorrect is not highly usable for practising RTL languages, as the text direction of all posts is fixed to the GUI base direction of left-to-right.
![](https://i.ibb.co/7QXrtmv/Screenshot-2023-11-12-115908.png)
## Improvement
Add `dir="rtl"` to posts marked as being written in RTL languages. Note: although possible to do that via CSS through the `lang` attribute mentioned in https://github.com/LangCorrect/server/issues/310, it's not recommended by W3C as it's relatively important semantic information that should be preserved even without CSS being rendered.

See [Structural markup and right-to-left text in HTML: Setting direction on block elements](https://www.w3.org/International/questions/qa-html-dir#blockelements)

**Comment by danielzeljko** [comment]
It looks like we can set the text direction via a [template tag](https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#template-filters) (easiest) or a [filter](https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#get-language-info).

> {{ LANGUAGE_CODE|language_bidi }} (False)

related #315

**Comment by yue-dongchen** [comment]
Closing in favour of #315.
