### ISSUE TITLE
Let correctors edit their corrections

### ISSUE THREAD

**Issue by keyxcode** [LangCorrect/server#321]

**Comment by ee22abc** [comment]
There are sites that allow posters to edit their posts in a limited time period, like 15 sec. or was it 30 sec? I think that is a good feature.

**Comment by danielzeljko** [comment]
A corrector can already edit their corrections by revisiting the make a correction page. If users would like to edit their corrections on the post detail page that can be arranged, but this ticket would need to be updated.
