### ISSUE TITLE
Customize font size

### ISSUE THREAD

**Issue by alexcjwei** [LangCorrect/server#333]
I'd like to add a feature that lets users customize font sizes. I'd love to help contribute this and would like some input as to how to design this.

I find the Chinese characters to be a bit too small and I have to strain and see. Adding this feature should not be too much effort but will improve the accessibility of the site to the vision-impaired, and be a quality-of-life improvement for other users.

At its most basic, we could have a user setting for font size, adding `FontSizeChoices` say of small, medium, and large and a `font_size` field to the `User` model. I think this should probably be in a separate `UserSettings`, but I see other settings there so I'm guessing it's fine?

I'm not entirely sure what the best way is to then apply this user setting to change the styling. It would be great to get input on this!

Maybe we could modify [post_detail.html](langcorrect/templates/posts/post_detail.html), adding `"font-size-text display-{{ font_size }}"` to the class of things we want to modify. Then defining the classes `font-size-text` and `display-small`, `display-medium`, `display-large` to [project.css](langcorrect/static/css/project.css)? Again, not sure what the cleanest way is.

I'm also not entirely sure how many components this should apply to on the website besides just `post_detail.html`.

**Comment by danielzeljko** [comment]
Your approach of using user specified font sizes would offer more personalization and control, and should definitely be in its own `UserSettings` table as you have mentioned. We could also leverage this table for other personalizations like #223, #315 and #176. IIRC, the default font size is 16px throughout the site. Which display-* would this map to? I'm worried that we may run into situations where display-large would work for some languages and look way too large in others.

Can you clarify `font-size-text`? BS already provides some utility classes to quickly change font sizes, line heights and more: https://getbootstrap.com/docs/5.3/utilities/text/#font-size. This could be something to leverage depending on the approach we take.

The only downside I can see from the approach we have here is that we are straying away from the more conventional approach which is using the browser settings and `rem` units. With this approach we would just need to ensure that the CSS is flexible enough to handle font size changes. This would have less of a performance impact.

**Comment by alexcjwei** [comment]
Browser settings and `rem` units is a good shout -- maybe this should just defer to users' browser settings, as users with visibility impairments have likely already made such adjustments on their browser...
