### ISSUE TITLE
Disable Post submit button on form submission

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#354]
![image](https://github.com/LangCorrect/server/assets/115326106/d0915a13-242e-4f5a-8eb8-661c05b0b47f)

**Comment by keyxcode** [comment]
Can you please clarify what's wrong here? It's not very obvious to me.

**Comment by danielzeljko** [comment]
This issue is about preventing duplicate posts. These duplicates can happen when a user clicks the "publish" button more than once, especially if their internet connection is slow. This causes the form to be sent multiple times. When someone tries to view these posts, there's a server error because get() will return more than one object. The goal is to stop this by disabling the "publish" button once the button is clicked.
