### ISSUE TITLE
Redirect to feed after logging in

### ISSUE THREAD

**Issue by keyxcode** [LangCorrect/server#356]
Currently users are redirected to their own profile page after logging in. I think it would make more sense to take them directly to the feed since that's where they spend most of their time.

**Comment by jimkalis16** [comment]
hi i would like to work on that if thats ok with you but i dont thing i can test it whith my pc could you assign it?

**Comment by danielzeljko** [comment]
@jimkalis16 Can you clarify what you mean by not being able to test it on your PC? Are you having troubles getting the project run locally?

**Comment by jimkalis16** [comment]
> @jimkalis16 Can you clarify what you mean by not being able to test it on your PC? Are you having troubles getting the project run locally?

my laptop is bad and it will catch on fire if i run it 🥲

**Comment by danielzeljko** [comment]
It's all coolio on my end!

**Comment by jimkalis16** [comment]
thank you i will start working on it
