### ISSUE TITLE
Notification bell shows notifications while there are none

### ISSUE THREAD

**Issue by keyxcode** [LangCorrect/server#401]
This seems to occur randomly, and the 'fake' notifications consistently disappear after I refresh the page or navigate to a different page.
One observation is that I have encountered this problem exclusively in the production environment, and not in the local version.

**Comment by pasieka-chorzele** [comment]
The same is happening to me, as if somebody else's notification count was showing.  It seems to happen only after a longer delay between refreshes.

**Comment by danielzeljko** [comment]
@keyxcode can you provide some of your finds here, so we can have information centralized here?


Some notes:

- We use https://pypi.org/project/django-notifications-hq/ for notifications, and it's currently does not support our Django version (v4.2)
- Package uses caching, could it be related to stale data?
- The template tag that renders the notification count queries the count from `request.user` object

**Comment by keyxcode** [comment]
I encountered the bug again today @danielzeljko

**Comment by danielzeljko** [comment]
I just released a temp fix (#463) which grabs the unread notification count directly from the DB without going through the cache mechanism. If you encounter the bug again, then we can rule out the cache.
