### ISSUE TITLE
Post tags are missing

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#414]
Post tags are not being displayed. Ideally they should be clickable to search posts containing the tag.

**Comment by alexcjwei** [comment]
Would you mind sketching out your ideal UI?

I'm thinking something like this by modifying `post_card.html`
<img width="874" alt="Screenshot 2024-01-17 at 12 00 27 PM" src="https://github.com/LangCorrect/server/assets/59217250/c32356ff-fd2d-4b6d-af72-42835baf9874">

Quick implementation looks like below.
<img width="421" alt="Screenshot 2024-01-17 at 12 03 24 PM" src="https://github.com/LangCorrect/server/assets/59217250/acd6aebe-e160-412f-846d-71e39342531f">

Any suggestions on styling / where this should go on a post?

Then there's the next part which is actually doing a search when clicked.

**Comment by danielzeljko** [comment]
I prefer to have the footer be very minimal so we can more easily see at a glance vital information. I'm worried if we were to add the tags there it'll either become too cluttered or it may take up `y` rows depending on how long the tags are or how many tags are attached to a post.

If we were to add the tags to be right above the footer, then we'll have much more horizontal space to work with. I do not have a preference for how the tags themselves should look like, so feel free to to play around with it or design something you like!

![image](https://github.com/LangCorrect/server/assets/115326106/f9980f6c-578d-41ea-b65a-10819cf6cfcd)

Here are some tags that I found for your convenience and inspiration:

![image](https://github.com/LangCorrect/server/assets/115326106/338530a0-abc6-40fa-9f64-7ff6b3213a2b)

![image](https://github.com/LangCorrect/server/assets/115326106/f92173b2-9ba0-44c9-bf9a-f5d559e77faa)

![image](https://github.com/LangCorrect/server/assets/115326106/b8231ef0-042d-4546-b633-acb855260e49)

There are also some examples found in this article with some UX/UI guidelines if you're interested: https://pixso.net/tips/tags-ui/.

(badges are pretty cool when I think about it!)

**Comment by alexcjwei** [comment]
I added some badges in https://github.com/LangCorrect/server/pull/427

How do you think searching by tags would work? Not quite convinced by the utility that would bring

**Comment by danielzeljko** [comment]
I find it may be beneficial for users to "filter" for things they're interested in. For example, a corrector may click on a tag to find posts that they're interested in correcting, or a learner may use it to find posts written by students that share the same interest as them. I'm not quite sure what the right approach would be to handle this feat, but here are two quick examples I came up with:

### A
Filter bar is displayed right before the post cards and readily available. If the tag is clicked, then perhaps the teach mode's filter would be shown with the tag option selected and the tag shown in the active filters.

![image](https://github.com/LangCorrect/server/assets/115326106/fee4baf3-388d-43d1-a2f0-bb97a85d6458)

### B
We can have a explore or search page. Might need to find some inspiration from how other sites handle this.

![image](https://github.com/LangCorrect/server/assets/115326106/188bea37-6eb5-425c-a1e8-80d17b468e20)

I'm open to suggestions!

**Comment by keyxcode** [comment]
Hey guys! I do have some thoughts on this, in no particular order:
- I think tags would become very useful when we have a significant number of uncorrected posts. At the current state of LC, I don't think this is the case in most languages (?) so I'd agree that this use case for now doesn't seem convincing. I imagine that most correctors just glance at the 5-10 uncorrected posts in their feed and can easily tell which one they like to pick based on their title and snippet.
- The use case where a learner tries to find posts with that topic does seem more convincing to me however. This might be particularly helpful for those who are prepping for standardized exams.

**Comment by keyxcode** [comment]
Some more thoughts on the design and implementation:
- We should limit the number of tags a user can include in a post. Ideally, there should be suggestions of existing tags showing up as they type to maintain some consistency. But I understand this might not be easy to implement.
- I do like the idea of an advanced search bar that doesn't show up all the time but is there when you need it.
- Here's an example of a design for an explore/ trending tags section: https://keyxcode.github.io/baguette-code/ (this is from a template). I think the trending tags idea is quite nice because obviously we can't show all of the tags, which can keep growing infinitely!

**Comment by danielzeljko** [comment]
I've moved this discussion to a separate issue: https://github.com/LangCorrect/server/issues/440
