### ISSUE TITLE
I can't find the way to reset password

### ISSUE THREAD

**Issue by ee22abc** [LangCorrect/server#418]
This may be more a question than a suggestion or request, but as I said above, I don't know how to reset my password here. 
I looked around as much as I can, but I don't find the place for it.

I just experienced an issue with a site, which seems to have resolved itself for now. However, I want to change my password because having a compromised account is no good, even when no money is involved.

PS: I've successfully changed my password by clicking the 'forgot password?'. From there I was taken to the page that says 'reset password'.

**Comment by keyxcode** [comment]
@ee22abc Currently, you can't change your password directly on the profile page (we will work on adding that). However, I'm glad you found a workaround. Could you describe the security issue you were having here or at support[at]langcorrect.com ?

**Comment by danielzeljko** [comment]
There are currently two ways to change your password:
- password reset link found in the login page
- https://langcorrect.com/accounts/password/change/

Nice find with the missing button. I'm not sure how that passed by me. Let's add this button (@keyxcode)

By "experienced an issue with a site", did you mean a different site and not LangCorrect? If it's about LC, feel free to message support as CP has said.
