### ISSUE TITLE
Add confirm dialog to "delete all my notificatins" button

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#422]
> When I click inside my notifications on the button "delete all my notificatins" (in the German version "Alle Benachrichtigungen löschen", it would make sense to ask back "Are you sure? (Y/N)". It is all too easy to accidentally click on the delete button, when one wants instead to open the last (bottommost) notification. Once they are deleted, I can not recall them anymore.

**Comment by keyxcode** [comment]
This is related to #402
I think with a page to view notifications and better button labels, this wouldn't be necessary

**Comment by keyxcode** [comment]
I think we can mark this as solved because the new notifications modal design no longer has a "delete all" option @danielzeljko
