### ISSUE TITLE
Minimum character count in Chinese

### ISSUE THREAD

**Issue by keyxcode** [LangCorrect/server#442]
https://langcorrect.com/journals/word-count/

> I write a few words in LangCrrect also in Chinese.
Someone corrected me my post then I wrote a comment “謝謝” means thank you, however I couldn’t post the message because the system said ‘Message needs to be at least 10 characters long.’
Then I wrote “謝謝您的指正” means thank you for your corrections, but there weren’t enough characters yet.
However there are the people who can post messages less 10 characters.
I wonder how I can do.

**Comment by danielzeljko** [comment]
> The problem is, in Chinese, most words consist of just one or two characters each, so a 10-character minimum is effectively a 5 to 10 word minimum for Chinese. This forces Chinese comments to be unnaturally wordy. We can’t, for example, simply say “thank you for your corrections” (5 words and 26 characters in English) because the equivalent Chinese phrase, 謝謝您的指正 (to borrow milky way’s example), consists of just 6 characters. Nor can we reply “you’re welcome” (13 characters in English) because the Chinese equivalent is just 3 characters long: 不客氣

**Comment by danielzeljko** [comment]
> Here the posts
>https://langcorrect.com/journals/%E5%9C%A8%E9%A4%90%E5%BB%B3/
> https://langcorrect.com/journals/%E5%A4%A9%E6%96%87%E9%A4%A8/

> There seems to be a slight misunderstanding. The text under the "Feedback" section is different from a reply. It's added separately by a corrector on the "Make a Correction" page. This is why they can write "寫得很好！" without seeing a minimum character count error.

Closing as it is not an issue. The text in question was not a reply, but rather text from the overall feedback section.
