### ISSUE TITLE
Lower min char requirement for replies

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#566]
> I don't know if this is the right place to ask - but is there any way the minimum required characters to post a reply to someone's correction when using Chinese/Japanese can be lowered/removed?

> In Chinese the correct way to say "Thank you" is "谢谢" which registers as only 2 characters, well short of the minimum 10.  I even just tried to post "谢谢！你总是帮助我" and was rejected because it's 9 chars ... except it means "Thank you!  You always help me" which is 30 chars in English.  I had to add a full stop to make it count.  This arbitrary limit often stops me saying thanks to people who help simply because I don't want to have think up a long sentence, or bother adding loads of unnecessary punctuation simply to hit the character limits.  The fact others get to say "Thank you!" to me when I correct there English, but I must think up two or three full sentences really bugs me lol

**Comment by DzSom02** [comment]
I'm a Chinese learner and it happens to me too! Not sure what it's a good solution, because I understand why there is a limit on the replies, perhaps allowing some standard replies like "谢谢"， but that does not sound easy or clean to implement...

Easier would be to delete the limit completely
