### ISSUE TITLE
I don't receive any feedback or correction.

### ISSUE THREAD

**Issue by tramdo26** [LangCorrect/server#582]
I have bought the premium package on Langcorrect. Recently, when I wrote 5 tasks, but I didn't receive any corrections. It's a little bit weird because it has been a week, and no one corrects my writing. It never happened before. 

When I read the terms, it stated that the premium package can receive unlimited feedback. However, it does not work for me, I guess. What should I do now?

**Comment by danielzeljko** [comment]
Hi,

Thank you for reaching out. The only thing that is stated is unlimited peer reviews, and it does not mention that corrections are guaranteed. After all, it's a community-driven platform where users help correct one another, and we have no direct say in who gets corrected and when.

Could you let me know which language you're writing in? Sometimes native speakers take breaks, and it may take longer to receive corrections for less popular languages.

**Comment by danielzeljko** [comment]
I'm closing this since it's not related to an issue with site functionality. Feel free to reach out to support@langcorrect.com if you have any more questions.
