### ISSUE TITLE
Create a Page to Display User-Submitted Prompts

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#71]
We need a dedicated page to display all prompts submitted by a user. This will make it easier for users to manage their submitted prompts.

As a user, I would like to be able to view all of my submitted prompts in one place, the ability to filter the prompts, and easily manage them.

- [ ] New route `/submissions/prompts`
- [ ] Display a list of all prompts submitted by the user
- [ ] Update the nav item link to point to this new page

![image](https://github.com/LangCorrect/server/assets/115326106/d9789aa1-d596-4a92-947e-3abfbd678177)

**Comment by keyxcode** [comment]
I would love to take on this one @danielzeljko

**Comment by danielzeljko** [comment]
Thanks for taking it on! 💯

**Comment by keyxcode** [comment]
Hey @danielzeljko as I looked at most of the prompts on LC, I felt like most of them were open-ended, simple questions that could be responded at any level of language, from 3 sentences to an entire essay. My conclusion is that the difficulty level lies more in the responses themselves and has little to do with the prompts. Therefore I suggest dropping the Difficulty column in this page, and prompt's difficulty level in general.

Please lmk what you think!

**Comment by danielzeljko** [comment]
Hi @keyxcode, you make a good point about the difficulty being reflected in the responses rather than the prompts themselves. However, I think some prompts are just naturally more challenging and kind of set the stage for the level of difficulty demanding more complex language and thought processes. Maybe we can have a balanced approach, possibly allowing users to tag the difficulty themselves or even using analytics to dynamically adjust it. This is definitely a bigger topic and should have its own separate issue. I personally like having difficulty levels because they can help me keep track of my progress. We can remove (not show) the difficulty column in the table, but let's hold off on removing it in general.
