### ISSUE TITLE
Create a Page to Display User-Submitted Posts

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#72]
Create a dedicated page for users to manage and review their journal entries.

As a user, I want a centralized page where I can see all of my journal entries in a table for easier management and review.

- [ ] Create a new route: `/submissions/posts` (TBD)
- [ ] List all journal entries submitted by the current user
- [ ] Provide options to view, edit, or delete each journal entry

Here's an example of how the old one used to look like:

![image](https://github.com/LangCorrect/server/assets/115326106/5e8f0cda-b931-4188-a6f6-328d6d4af2bd)

**Comment by chrismathew047** [comment]
Hi @danielzeljko, 

Hope you are doing well. Can i work on this?

**Comment by danielzeljko** [comment]
Welcome to the project, @chrismathew047! I've assigned this issue to you. Feel free to reach out with any questions in our Discord dev channel - https://discord.gg/Vk7KcV26Fe. Thanks for contributing!
